### ISSUE TITLE
How does this translate to a querystring?

### ISSUE THREAD

**Issue by svendeckers** [arve0/feathers-nedb-fuzzy-search#3]
Hi,

I'm using the Fetch API in a React app to query my Feathers api/Nedb.

I've installed the fuzzy-search module and followed the complete example, but I can't figure out how to compose the URL for fetch (or Postman when testing).
I've tried the following: 
1) `http://localhost:3030/messages?$search=john` but get the error `Unknown logical operator $search`
2) `http://localhost:3030/messages?query=$search[john]` but get an empty result.
3) `http://localhost:3030/messages?search=john` but get an empty result as well.

Could you please provide an example?
Thank you on beforehand :-)

**Comment by arve0** [comment]
Correct usage should be:

```
curl http://localhost:3030/messages?$search=qwerty
```

How is the app setup?

**Comment by svendeckers** [comment]
Thanks for your swift reply! 
When I use your string in Postman, it works :-) 
It doesn't with curl though (I get everything returned), but maybe that has to do with the '$' sign on command line or something... 
Anyways, I should be able to take it from here, thanks again!

**Comment by svendeckers** [comment]
For the record: it works 👍

**Comment by trinly01** [comment]
what is the solution?

**Comment by svendeckers** [comment]
didn't have one for curl iirc, but postman did the trick for me during testing
